config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :players, controllers: { omniauth_callbacks: 'authentication' }

  devise_scope :player do
    mount Sidekiq::Web => "/sidekiq" # TODO protect view to only admins https://github.com/mperham/sidekiq/wiki/Monitoring#devise
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    namespace :admin do
      authenticated :player do
        constraints(AdminConstraint) do
          resources :quotes

          resources :players

          root to: "base#index"
        end
      end

      # Default to base#index, which for non authenticated users will redirect to /
      get "*path", to: redirect("/")
    end
  end

  mount OMG::API => '/'

  mount ActionCable.server => '/cable'

  # # Allow activestorage blob paths
  # scope ActiveStorage.routes_prefix do
  #   get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  # end

  root "main#index"
  get '*path', to: "main#index", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id                                                 :bigint           not null, primary key
#  avatar(Player avatar url)                          :text
#  current_sign_in_at                                 :datetime
#  current_sign_in_ip                                 :string
#  last_sign_in_at                                    :datetime
#  last_sign_in_ip                                    :string
#  name(Player screen name)                           :string
#  provider(Omniauth provider)                        :string
#  remember_created_at                                :datetime
#  role(Player role for permissions)                  :string           not null
#  sign_in_count                                      :integer          default(0), not null
#  total_vps_earned(Total WAR VPs earned, not capped) :integer          default(0), not null
#  uid(Omniauth uid)                                  :string
#  vps(WAR VPs earned up to ruleset max)              :integer          default(0), not null
#  created_at                                         :datetime         not null
#  updated_at                                         :datetime         not null
#  discord_id(Discord id)                             :string
#
# Indexes
#
#  index_players_on_provider_and_uid  (provider,uid) UNIQUE
#
class Player < ApplicationRecord
  include ActiveModel::Serializers::JSON
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :rememberable, :trackable, :timeoutable, :omniauthable, omniauth_providers: %i[steam]

  def self.from_omniauth(auth)
    player = find_by(provider: auth.provider, uid: auth.uid)
    if player.present?
      # Rails.logger.info("Player found from omniauth: #{player.name}")
      player.name = auth.info.nickname
      player.avatar = auth.info.image
      player.save!
    else
      pdt = PlayerDiscordTemp.find_by(player_name: auth.info.nickname)
      player = create!(provider: auth.provider, uid: auth.uid, name: auth.info.nickname, avatar: auth.info.image, discord_id: pdt&.discord_id, role: roles[:player])
      # Rails.logger.info("Player created from omniauth: #{player.name}")

      # try to match nickname to historical player rating with nil player_id
      hpr = HistoricalPlayerRating.find_by(player_name: player.name.upcase, player_id: nil)
      if hpr.present?
        # Rails.logger.info("Found historical player rating for player #{player.name}")
        PlayerRating.create!(player: player, elo: hpr.elo, mu: hpr.mu, sigma: hpr.sigma, last_played: hpr.last_played)
        hpr.update!(player_id: player.id)
      else
        # Rails.logger.info("Created default PlayerRating for player #{player.name}")
        PlayerRating.for_new_player(player)
      end
    end

    player.remember_me!
    player
  end

  enum role: {
    player: "player",
    admin: "admin"
  }

  has_many :companies, inverse_of: :player
  has_many :doctrines, through: :companies
  has_many :factions, through: :companies
  has_one :player_rating, inverse_of: :player
  has_many :historical_player_ratings, inverse_of: :player
  has_many :historical_battle_players, inverse_of: :player

  scope :online, -> { where("updated_at > ? ", 10.minutes.ago) }

  def entity
    Entity.new(self)
  end

  class Entity < Grape::Entity
    expose :id
    expose :name
    expose :avatar
    expose :role
  end
end

app/models/ratings/player.rb
module Ratings
  class Player
    attr_accessor :name, :ts_rating, :last_played, :games_played, :wins, :losses

    def initialize(name, ts_rating)
      @name = name
      @ts_rating = ts_rating
      @last_played = nil
      @games_played = 0
      @wins = 0
      @losses = 0
    end

    def update_ts_rating(ts_rating, last_played)
      @ts_rating = ts_rating
      @last_played = last_played
    end

    def update_win_loss(is_win)
      @wins += is_win ? 1 : 0
      @losses += is_win ? 0 : 1
      @games_played += 1
    end
  end
end

app/models/skill/player.rb
module Skill
  class Player
    attr_accessor :name, :ts_rating, :last_played, :games_played, :wins, :losses

    def initialize(name, ts_rating)
      @name = name
      @ts_rating = ts_rating
      @last_played = nil
      @games_played = 0
      @wins = 0
      @losses = 0
    end

    def update_ts_rating(ts_rating, last_played)
      @ts_rating = ts_rating
      @last_played = last_played
    end

    def update_win_loss(is_win)
      @wins += is_win ? 1 : 0
      @losses += is_win ? 0 : 1
      @games_played += 1
    end
  end
end

app/controllers/admin/players_controller.rb
module Admin
  class PlayersController < AdminController
    before_action :set_player, only: %i[show edit update destroy]

    def index
      @players = Player.includes(:player_rating).order(:name)
    end

    def show

    end

    def edit

    end

    def update
      service = Admin::PlayerService.new(@player)
      if service.update(player_params, player_rating_params)
        respond_to do |format|
          format.html { redirect_to admin_players_path, notice: "Player was successfully updated." }
          format.turbo_stream { flash.now[:notice] = "Player was successfully updated." }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_player
      @player = Player.includes(:player_rating).find(params[:id])
    end

    def player_params
      params.require(:player).permit(:discord_id)
    end

    def player_rating_params
      params.require(:player_rating).permit(:elo_override)
    end
  end
end

app/controllers/api/player_controller.rb
module API
  class PlayerController < APIController
    before_action :authenticate_player!

    def index
    render json: current_player.serializable_hash(only: [:id, :name, :avatar])
    end
  end
end

app/controllers/api/v1/player_controller.rb
module Api
  module V1
    class PlayerController < ApplicationController
      def index
        render json: current_player.serializable_hash(only: [:id, :name, :avatar])
      end
    end
  end
end

app/controllers/players/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :verify_authenticity_token
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed
  end

  def register_success
    render json: { message: 'Signed up sucessfully.' }
  end

  def register_failed
    render json: { message: "Something went wrong." }
  end
end

app/controllers/players/sessions_controller.rb
class Players::SessionsController < Devise::SessionsController
  skip_before_action :verify_authenticity_token
  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: { message: 'Logged in' }, status: :ok
  end

  def respond_to_on_destroy
    log_out_success && return if current_player

    log_out_failure
  end

  def log_out_success
    render json: { message: 'Logged out' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Nothing happened' }, status: :unauthorized
  end
end

app/views/admin/players/_form.html.erb
<div class="player row">
  <%= simple_form_for [:admin, player], html: { class: "form", novalidate: true } do |f| %>
    <% if player.errors.any? %>
      <div class="alert alert-danger" role="alert">
        <%= quote.errors.full_messages.to_sentence.capitalize %>
      </div>
    <% end %>

    <div class="row">
      <div class="col">
        <%= player.name %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.input :discord_id, label: "Discord ID", required: false %>
      </div>
      <div class="col">
        <%= simple_fields_for :player_rating do |o| %>
          <%= o.input :elo_override, as: :integer, input_html: { value: player.player_rating.elo_override }, label: "Override Elo", required: false %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.submit class: "btn btn-secondary btn-sm submit float-end" %>
        <%= link_to "Cancel", admin_players_path, class: "btn btn-light btn-sm float-end" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/players/_player.html.erb
<%= turbo_frame_tag player do %>
  <div class="player row">
    <div class="col">
<!--      No player show page yet-->
      <%#= link_to player.name, admin_player_path(player), data: { turbo_frame: "_top"} %>
      <%= player.name %>
    </div>
    <div class="col">
      <%= player.current_sign_in_at %>
    </div>
    <div class="col">
      <%= player.discord_id || "" %>
    </div>
    <div class="col">
      <%= player.player_rating.elo_override %>
    </div>
    <div class="col-1">
      <div class="row">
        <div class="col">
          <%= link_to "Edit", edit_admin_player_path(player), class: "btn btn-light btn-sm" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/players/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to player"), admin_player_path(@player) %>

  <div class="header">
    <h1>Edit Player</h1>
  </div>

  <%= turbo_frame_tag @player do %>
    <%= render "form", player: @player %>
  <% end %>
</main>

app/views/admin/players/index.html.erb
<main class="container">
  <div class="header row">
    <div class="col">
      <h1>Players</h1>
    </div>
    <div class="col">
      Last Sign In
    </div>
    <div class="col">
      Discord ID
    </div>
    <div class="col">
      Elo Override
    </div>
    <div class="col-1">

    </div>
  </div>

  <%= turbo_frame_tag "players" do %>
    <%= render @players %>
  <% end %>

  <%= turbo_stream_from "players" %>
</main>

app/views/admin/players/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to Players"), admin_players_path %>
  <div class="header">
    <h1>
      <%= @player.name %>
    </h1>
  </div>
</main>

app/views/admin/players/update.turbo_stream.erb
<%= turbo_stream.replace @player %>

<%= render_turbo_stream_flash_messages %>