config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :players, controllers: { omniauth_callbacks: 'authentication' }

  devise_scope :player do
    mount Sidekiq::Web => "/sidekiq" # TODO protect view to only admins https://github.com/mperham/sidekiq/wiki/Monitoring#devise
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    namespace :admin do
      authenticated :player do
        constraints(AdminConstraint) do
          resources :quotes

          resources :players

          root to: "base#index"
        end
      end

      # Default to base#index, which for non authenticated users will redirect to /
      get "*path", to: redirect("/")
    end
  end

  mount OMG::API => '/'

  mount ActionCable.server => '/cable'

  # # Allow activestorage blob paths
  # scope ActiveStorage.routes_prefix do
  #   get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  # end

  root "main#index"
  get '*path', to: "main#index", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/models/quote.rb
# == Schema Information
#
# Table name: quotes
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Quote < ApplicationRecord
  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  # # After a new quote is committed to the DB,
  # # render the quotes/quotes.html.erb partial in the turbo_stream format with action prepend and target "quotes"
  # # Run async as a Turbo::Streams::BroadcastJob
  # after_create_commit -> { broadcast_prepend_later_to "quotes" }
  # # is the same as:
  # # after_create_commit -> { broadcast_prepend_to "quotes", partial: "admin/quotes/quote", locals: { quote: self }, target: "quotes" }
  # # by convention, target name is model_name.pluralize, so don't need to include
  # # by convention, partial path is equal to calling #to_partial_path on an instance of the model
  # # by convention, the locals default value is equal to model_name.element.to_sym => self
  #
  # after_update_commit -> { broadcast_replace_later_to "quotes" }
  # after_destroy_commit -> { broadcast_remove_to "quotes" }

  # is the same as:
  broadcasts_to ->(quote) { "quotes" }, inserts_by: :prepend
  # Users that should share the same broadcast should have the lambda return an array with the same values

  # Override to_partial_path
  def to_partial_path
    "admin/quotes/quote"
  end
end

app/controllers/admin/quotes_controller.rb
module Admin
  class QuotesController < AdminController

    before_action :set_quote, only: [:show, :edit, :update, :destroy]

    def index
      @quotes = Quote.ordered
    end

    def show
    end

    def new
      @quote = Quote.new
    end

    def create
      @quote = Quote.new(quote_params)

      if @quote.save
        respond_to do |format|
          format.html { redirect_to admin_quotes_path, notice: "Quote was successfully created." }
          format.turbo_stream { flash.now[:notice] = "Quote was successfully created." } # Use flash#now because turbo stream doesn't redirect
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    def edit
    end

    def update
      if @quote.update(quote_params)
        # redirect_to admin_quotes_path, notice: "Quote was successfully updated."
        respond_to do |format|
          format.html { redirect_to admin_quotes_path, notice: "Quote was successfully updated." }
          format.turbo_stream { flash.now[:notice] = "Quote was successfully updated." }
        end
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @quote.destroy
      respond_to do |format|
        format.html { redirect_to admin_quotes_path, notice: "Quote was successfully destroyed." }
        format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed." }
      end
    end

    private

    def set_quote
      @quote = Quote.find(params[:id])
    end

    def quote_params
      params.require(:quote).permit(:name)
    end
  end
end

app/views/admin/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>
  <%= link_to "Add Quote",
              new_admin_quote_path,
              class: "btn btn-primary",
              data: { turbo_frame: dom_id(Quote.new) } %>
</div>

app/views/admin/quotes/_form.html.erb
<%= simple_form_for [:admin, quote], html: { class: "quote form" } do |f| %>
  <% if quote.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <%= quote.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <div class="row">
    <div class="col-8">
      <%= f.input :name, input_html: { autofocus: true } %>
    </div>
    <div class="col">
      <%= link_to "Cancel", admin_quotes_path, class: "btn btn-light" %>
    </div>
    <div class="col">
      <%= f.submit class: "btn btn-secondary" %>
    </div>
  </div>
<% end %>

app/views/admin/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote row">
    <div class="col">
      <%= link_to quote.name, admin_quote_path(quote), data: { turbo_frame: "_top" } %>
    </div>
    <div class="col-2">
      <div class="row">
        <div class="col">
          <%= link_to "Edit",
                      edit_admin_quote_path(quote),
                      class: "btn btn-light" %>
        </div>
        <div class="col">
          <%= button_to "Delete",
                        admin_quote_path(quote),
                        method: :delete,
                        form: { data: { turbo_frame: "_top" } },
                        class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/quotes/create.turbo_stream.erb
<%# prepend the created quote to the dom node with id "quotes" %>
<%= turbo_stream.prepend "quotes", @quote %>

<!--same thing as above line-->
<%#= turbo_stream.prepend "quotes" do %>
  <%#= render partial: "admin/quotes/quote", locals: { quote: @quote } %>
<%# end %>

<%# empty the contents of the dom node with id "new_quote" %>
<%= turbo_stream.update Quote.new, "" %>

<%# prepend the contents of the flash message to the dom node with id "flash" %>
<%= render_turbo_stream_flash_messages %>

app/views/admin/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

<%= render_turbo_stream_flash_messages %>

<%# unless Quote.exists? %>
  <%#= turbo_stream.update Quote.new do %>
    <%#= render "admin/quotes/empty_state" %>
  <%# end %>
<%# end %>

app/views/admin/quotes/edit.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quote"), admin_quote_path(@quote) %>

  <div class="header">
    <h1>Edit quote</h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/admin/quotes/index.html.erb
<main class="container">
  <div class="header row">
    <div class="col">
      <h1>Quotes</h1>
    </div>
    <div class="col">
      <%= link_to "New quote",
                  new_admin_quote_path,
                  data: { turbo_frame: dom_id(Quote.new) },
                  class: "btn btn-primary float-end" %>
    </div>
  </div>

  <%= turbo_frame_tag Quote.new do %>
    <%# if @quotes.none? %>
      <%#= render "admin/quotes/empty_state" %>
    <%# end %>
  <% end %>

  <%= turbo_frame_tag "quotes" do %>
    <%= render "admin/quotes/empty_state" %>
    <%= render @quotes %>
  <% end %>

  <%# Generates a custom element to subscribe to the channel name %>
  <%= turbo_stream_from "quotes" %>
</main>

app/views/admin/quotes/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), admin_quotes_path %>

  <div class="header">
    <h1>New quote</h1>
  </div>

  <%= turbo_frame_tag @quote do %>
    <%= render "form", quote: @quote %>
  <% end %>
</main>

app/views/admin/quotes/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to quotes"), admin_quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/admin/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>

<%= render_turbo_stream_flash_messages %>