config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :players, controllers: { omniauth_callbacks: 'authentication' }

  devise_scope :player do
    mount Sidekiq::Web => "/sidekiq" # TODO protect view to only admins https://github.com/mperham/sidekiq/wiki/Monitoring#devise
    delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session

    namespace :admin do
      authenticated :player do
        constraints(AdminConstraint) do
          resources :quotes

          resources :players

          root to: "base#index"
        end
      end

      # Default to base#index, which for non authenticated users will redirect to /
      get "*path", to: redirect("/")
    end
  end

  mount OMG::API => '/'

  mount ActionCable.server => '/cable'

  # # Allow activestorage blob paths
  # scope ActiveStorage.routes_prefix do
  #   get "/blobs/redirect/:signed_id/*filename" => "secure_blobs#show"
  # end

  root "main#index"
  get '*path', to: "main#index", constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert <%= flash_type == :alert ? "alert-danger" : "alert-info" %> alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if player_signed_in? %>
    <div class="navbar-brand">
      OMG Admin
    </div>
    <div class="navbar-name">
      <%= current_player.name %>
    </div>
    <%= button_to "Sign Out",
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn-dark" %>
  <% else %>
    <%= link_to "Return to App", to: "/", class: "btn btn-dark navbar-right" %>
  <% end %>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
<head>
  <title>OMGRails Admin</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <%= favicon_link_tag asset_path("favicon.ico") %>
  <%= stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
</head>

<body>
<%= render "layouts/navbar" %>

<div class="container">
  <div id="flash">
    <%= render "layouts/flash" %>
  </div>
</div>

<%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OMGRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <%= favicon_link_tag asset_path("favicon.ico") %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_tag 'index' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>